import fs from 'fs';

export const DOMESTIC_PUMPS = [
  { product_name: 'MINI 30C', kw: '0.37', hp: '0.5', pipe_size: '25 x 25 mm', head: '6-27 m', flow_rate: '500-2400 LPH', group_name: 'Domestic Mini Self Priming', category: 'DEWAS' },
  { product_name: 'MINI 40C', kw: '0.37', hp: '0.5', pipe_size: '25 x 25 mm', head: '6-36 m', flow_rate: '450-2500 LPH', group_name: 'Domestic Mini Self Priming', category: 'DEWAS' },
  { product_name: 'MINI 40C ES', kw: '0.37', hp: '0.5', pipe_size: '25 x 25 mm', head: '6-36 m', flow_rate: '450-2500 LPH', group_name: 'Domestic Mini Self Priming (Energy Saver)', category: 'DEWAS' },
  { product_name: 'MINI 50C', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: '6-45 m', flow_rate: '500-3400 LPH', group_name: 'Domestic Mini Self Priming', category: 'DEWAS' },
  { product_name: 'MINI 58C', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: '6-52 m', flow_rate: '500-3600 LPH', group_name: 'Domestic Mini Self Priming', category: 'DEWAS' },
  { product_name: 'JALRAAJ ULTRA', kw: '0.37', hp: '0.5', pipe_size: '25 x 25 mm', head: '6-32 m', flow_rate: '400-2400 LPH', group_name: 'Domestic Mini Self Priming', category: 'DEWAS' },
  { product_name: 'CHHOTU STAR ULTRA', kw: '0.37', hp: '0.5', pipe_size: '25 x 25 mm', head: '6-30 m', flow_rate: '450-2200 LPH', group_name: 'Domestic Mini Self Priming', category: 'DEWAS' },
  { product_name: 'JALRAAJ-I ULTRA', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: '6-42 m', flow_rate: '500-3200 LPH', group_name: 'Domestic Mini Self Priming', category: 'DEWAS' },
  { product_name: 'JALRAAJ-I ULTRA MAX', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: '6-48 m', flow_rate: '500-3500 LPH', group_name: 'Domestic Mini Self Priming', category: 'DEWAS' },
  { product_name: 'JALRAAJ-II ULTRA MAX', kw: '1.1', hp: '1.5', pipe_size: '25 x 25 mm', head: '6-54 m', flow_rate: '600-4000 LPH', group_name: 'Domestic Mini Self Priming', category: 'DEWAS' },
  { product_name: 'ANISA', kw: '0.37', hp: '0.5', pipe_size: '25 x 25 mm', head: '6-28 m', flow_rate: '400-2300 LPH', group_name: 'Domestic Mini Self Priming', category: 'DEWAS' },
  { product_name: 'ANNIKA', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: '6-44 m', flow_rate: '500-3300 LPH', group_name: 'Domestic Mini Self Priming', category: 'DEWAS' },
  { product_name: 'CHHOTU-I ULTRA', kw: '0.37', hp: '0.5', pipe_size: '25 x 25 mm', head: '6-30 m', flow_rate: '450-2200 LPH', group_name: 'Domestic Mini Self Priming', category: 'DEWAS' },
  { product_name: 'CHHOTU-II ULTRA', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: '6-42 m', flow_rate: '500-3100 LPH', group_name: 'Domestic Mini Self Priming', category: 'DEWAS' },
  { product_name: 'JALDAKSH', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: '6-45 m', flow_rate: '500-3400 LPH', group_name: 'Domestic Mini Self Priming - Jal Series', category: 'DEWAS' },
  { product_name: 'JALHASTI', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: '6-45 m', flow_rate: '500-3400 LPH', group_name: 'Domestic Mini Self Priming - Jal Series', category: 'DEWAS' },
  { product_name: 'JALTARA', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: '6-45 m', flow_rate: '500-3400 LPH', group_name: 'Domestic Mini Self Priming - Jal Series', category: 'DEWAS' },
  { product_name: 'JALHANSA', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: '6-45 m', flow_rate: '500-3400 LPH', group_name: 'Domestic Mini Self Priming - Jal Series', category: 'DEWAS' },
  { product_name: 'JALSENA', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: '6-45 m', flow_rate: '500-3400 LPH', group_name: 'Domestic Mini Self Priming - Jal Series', category: 'DEWAS' },
  { product_name: 'JALNAYAK', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: '6-45 m', flow_rate: '500-3400 LPH', group_name: 'Domestic Mini Self Priming - Jal Series', category: 'DEWAS' },
  { product_name: 'AQUA KNIGHT', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: '6-45 m', flow_rate: '500-3400 LPH', group_name: 'Domestic Self Priming Pumps', category: 'DEWAS' },
  { product_name: 'V-FLOW', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: '6-40 m', flow_rate: '500-3200 LPH', group_name: 'Domestic Self Priming Pumps', category: 'DEWAS' },
  { product_name: 'AQUA TORRENT-10FCL', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: '6-42 m', flow_rate: '500-3200 LPH', group_name: 'Domestic Self Priming Pumps', category: 'DEWAS' },
  { product_name: 'CMS N', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: '6-40 m', flow_rate: '500-3000 LPH', group_name: 'Domestic Self Priming Pumps', category: 'DEWAS' },
  { product_name: 'KJ-0524', kw: '0.37', hp: '0.5', pipe_size: '32 x 25 mm', head: '9-24 m', flow_rate: '350-1800 LPH', group_name: 'Domestic Deep Well Jet Pumps', category: 'DEWAS' },
  { product_name: 'KJ-1036', kw: '0.75', hp: '1.0', pipe_size: '32 x 25 mm', head: '12-36 m', flow_rate: '400-2400 LPH', group_name: 'Domestic Deep Well Jet Pumps', category: 'DEWAS' },
  { product_name: 'KJ-1548', kw: '1.1', hp: '1.5', pipe_size: '32 x 25 mm', head: '15-48 m', flow_rate: '500-3000 LPH', group_name: 'Domestic Deep Well Jet Pumps', category: 'DEWAS' },
  { product_name: 'LIFTER', kw: '0.75', hp: '1.0', pipe_size: '32 x 25 mm', head: '9-36 m', flow_rate: '400-2200 LPH', group_name: 'Domestic Shallow Well Pumps', category: 'DEWAS' },
  { product_name: 'LIFTER ULTRA', kw: '0.75', hp: '1.0', pipe_size: '32 x 25 mm', head: '9-38 m', flow_rate: '400-2400 LPH', group_name: 'Domestic Shallow Well Pumps', category: 'DEWAS' },
  { product_name: 'HI-LIFTER', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: '10-50 m', flow_rate: '300-2000 LPH', group_name: 'Domestic High Lift Pumps', category: 'DEWAS' },
  { product_name: 'KOSi-0515', kw: '0.37', hp: '0.5', pipe_size: '25 x 25 mm', head: '6-18 m', flow_rate: '50-180 LPM', group_name: 'Domestic Openwell Submersible Single Phase', category: 'DEWAS' },
  { product_name: 'KOSi-116', kw: '0.75', hp: '1.0', pipe_size: '40 x 32 mm', head: '8-22 m', flow_rate: '60-250 LPM', group_name: 'Domestic Openwell Submersible Single Phase', category: 'DEWAS' },
  { product_name: 'KOSi-125', kw: '0.75', hp: '1.0', pipe_size: '32 x 25 mm', head: '10-28 m', flow_rate: '50-200 LPM', group_name: 'Domestic Openwell Submersible Single Phase', category: 'DEWAS' },
  { product_name: 'KOSi-134', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: '12-36 m', flow_rate: '40-160 LPM', group_name: 'Domestic Openwell Submersible Single Phase', category: 'DEWAS' },
  { product_name: 'KOSi-1.522', kw: '1.1', hp: '1.5', pipe_size: '40 x 32 mm', head: '10-28 m', flow_rate: '60-280 LPM', group_name: 'Domestic Openwell Submersible Single Phase', category: 'DEWAS' },
  { product_name: 'KOSi-225', kw: '1.5', hp: '2.0', pipe_size: '50 x 40 mm', head: '12-30 m', flow_rate: '80-350 LPM', group_name: 'Domestic Openwell Submersible Single Phase', category: 'DEWAS' },
  { product_name: 'CPBS-1 Booster', kw: '0.37', hp: '0.5', pipe_size: '25 x 25 mm', head: 'Up to 32 m', flow_rate: 'Up to 2.5 m³/hr', group_name: 'Pressure Boosting System', category: 'DEWAS' },
  { product_name: 'CPBS-2 Booster', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: 'Up to 45 m', flow_rate: 'Up to 3.5 m³/hr', group_name: 'Pressure Boosting System', category: 'DEWAS' },
  { product_name: 'K-BOOSTER 0.5', kw: '0.37', hp: '0.5', pipe_size: '25 x 25 mm', head: 'Up to 30 m', flow_rate: 'Up to 2.2 m³/hr', group_name: 'Pressure Boosting System', category: 'DEWAS' },
  { product_name: 'K-BOOSTER 1.0', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: 'Up to 42 m', flow_rate: 'Up to 3.2 m³/hr', group_name: 'Pressure Boosting System', category: 'DEWAS' },
  { product_name: 'STAR GALAXY 0.5', kw: '0.37', hp: '0.5', pipe_size: '25 x 25 mm', head: 'Up to 28 m', flow_rate: 'Up to 2.0 m³/hr', group_name: 'Pressure Boosting System', category: 'DEWAS' },
  { product_name: 'STAR GALAXY 1.0', kw: '0.75', hp: '1.0', pipe_size: '25 x 25 mm', head: 'Up to 40 m', flow_rate: 'Up to 3.0 m³/hr', group_name: 'Pressure Boosting System', category: 'DEWAS' },
];

export const AGRICULTURE_PUMPS = [
  { product_name: 'KDS-114+ (1-Ph)', kw: '0.75', hp: '1.0', pipe_size: '50 x 50 mm', head: '6-14 m', flow_rate: '2.0-6.0 LPS', group_name: 'Agriculture Single Phase Monobloc', category: 'DEWAS' },
  { product_name: 'KDS-116+ (1-Ph)', kw: '0.75', hp: '1.0', pipe_size: '50 x 40 mm', head: '8-16 m', flow_rate: '2.0-5.5 LPS', group_name: 'Agriculture Single Phase Monobloc', category: 'DEWAS' },
  { product_name: 'KDS-214+ (1-Ph)', kw: '1.5', hp: '2.0', pipe_size: '65 x 50 mm', head: '8-18 m', flow_rate: '4.0-10.0 LPS', group_name: 'Agriculture Single Phase Monobloc', category: 'DEWAS' },
  { product_name: 'KDS-216+ (1-Ph)', kw: '1.5', hp: '2.0', pipe_size: '65 x 50 mm', head: '10-20 m', flow_rate: '3.5-9.0 LPS', group_name: 'Agriculture Single Phase Monobloc', category: 'DEWAS' },
  { product_name: 'KDS-314+ (1-Ph)', kw: '2.2', hp: '3.0', pipe_size: '80 x 80 mm', head: '8-16 m', flow_rate: '6.0-16.0 LPS', group_name: 'Agriculture Single Phase Monobloc', category: 'DEWAS' },
  { product_name: 'KAM-10', kw: '0.75', hp: '1.0', pipe_size: '50 x 50 mm', head: '6-12 m', flow_rate: '2.0-6.5 LPS', group_name: 'Agriculture Single Phase Monobloc', category: 'DEWAS' },
  { product_name: 'KAM-20', kw: '1.5', hp: '2.0', pipe_size: '65 x 50 mm', head: '8-16 m', flow_rate: '3.0-10.0 LPS', group_name: 'Agriculture Single Phase Monobloc', category: 'DEWAS' },
  { product_name: 'DC-1', kw: '0.75', hp: '1.0', pipe_size: '50 x 50 mm', head: '6-14 m', flow_rate: '2.5-6.0 LPS', group_name: 'Agriculture Single Phase Monobloc', category: 'DEWAS' },
  { product_name: 'DC-2', kw: '1.5', hp: '2.0', pipe_size: '65 x 50 mm', head: '8-18 m', flow_rate: '4.0-11.0 LPS', group_name: 'Agriculture Single Phase Monobloc', category: 'DEWAS' },
  { product_name: 'HASTI-1', kw: '0.75', hp: '1.0', pipe_size: '50 x 50 mm', head: '6-14 m', flow_rate: '3.0-7.0 LPS', group_name: 'Agriculture Single Phase Monobloc', category: 'DEWAS' },
  { product_name: 'HASTI-2', kw: '1.5', hp: '2.0', pipe_size: '65 x 50 mm', head: '8-18 m', flow_rate: '4.0-12.0 LPS', group_name: 'Agriculture Single Phase Monobloc', category: 'DEWAS' },
  { product_name: 'PAMBA PUZHA-1', kw: '0.75', hp: '1.0', pipe_size: '50 x 50 mm', head: '6-14 m', flow_rate: '2.5-6.5 LPS', group_name: 'Agriculture Single Phase Monobloc', category: 'DEWAS' },
  { product_name: 'PAMBA PUZHA-2', kw: '1.5', hp: '2.0', pipe_size: '65 x 50 mm', head: '8-18 m', flow_rate: '4.0-11.0 LPS', group_name: 'Agriculture Single Phase Monobloc', category: 'DEWAS' },
];

export const SUBMERSIBLE_BOREWELL_PUMPS = [
  { product_name: 'KP4 JALRAAJ UVA 0.5', kw: '0.37', hp: '0.5', pipe_size: '32 mm', head: '15-45 m', stages: '8', group_name: '4" Borewell Submersible Oil Cooled', category: 'DEWAS' },
  { product_name: 'KP4 JALRAAJ UVA 1.0', kw: '0.75', hp: '1.0', pipe_size: '32 mm', head: '25-75 m', stages: '14', group_name: '4" Borewell Submersible Oil Cooled', category: 'DEWAS' },
  { product_name: 'KP4 JALRAAJ UVA 1.5', kw: '1.1', hp: '1.5', pipe_size: '32 mm', head: '35-105 m', stages: '20', group_name: '4" Borewell Submersible Oil Cooled', category: 'DEWAS' },
  { product_name: 'KP4 JALRAAJ UVA 2.0', kw: '1.5', hp: '2.0', pipe_size: '32 mm', head: '45-135 m', stages: '25', group_name: '4" Borewell Submersible Oil Cooled', category: 'DEWAS' },
  { product_name: 'KU4-10', kw: '0.75', hp: '1.0', pipe_size: '32 mm', head: '20-60 m', group_name: '4" Borewell Submersible Oil Cooled', category: 'DEWAS' },
  { product_name: 'KU4-15', kw: '1.1', hp: '1.5', pipe_size: '32 mm', head: '30-90 m', group_name: '4" Borewell Submersible Oil Cooled', category: 'DEWAS' },
  { product_name: 'KU4-20', kw: '1.5', hp: '2.0', pipe_size: '38 mm', head: '40-120 m', group_name: '4" Borewell Submersible Oil Cooled', category: 'DEWAS' },
  { product_name: 'KU4-30', kw: '2.2', hp: '3.0', pipe_size: '38 mm', head: '60-180 m', group_name: '4" Borewell Submersible Oil Cooled', category: 'DEWAS' },
  { product_name: 'KS4-10', kw: '0.75', hp: '1.0', pipe_size: '32 mm', head: '20-65 m', group_name: '4" Borewell Submersible Water Cooled', category: 'DEWAS' },
  { product_name: 'KS4-15', kw: '1.1', hp: '1.5', pipe_size: '32 mm', head: '30-95 m', group_name: '4" Borewell Submersible Water Cooled', category: 'DEWAS' },
  { product_name: 'KS4-20', kw: '1.5', hp: '2.0', pipe_size: '38 mm', head: '40-130 m', group_name: '4" Borewell Submersible Water Cooled', category: 'DEWAS' },
  { product_name: 'KS4-30', kw: '2.2', hp: '3.0', pipe_size: '38 mm', head: '60-190 m', group_name: '4" Borewell Submersible Water Cooled', category: 'DEWAS' },
  { product_name: 'KS4-50', kw: '3.7', hp: '5.0', pipe_size: '50 mm', head: '80-240 m', group_name: '4" Borewell Submersible Water Cooled', category: 'DEWAS' },
  { product_name: 'NEO-10', kw: '0.75', hp: '1.0', pipe_size: '32 mm', head: '25-70 m', group_name: '4" Borewell Submersible Water Cooled', category: 'DEWAS' },
  { product_name: 'NEO-15', kw: '1.1', hp: '1.5', pipe_size: '32 mm', head: '35-100 m', group_name: '4" Borewell Submersible Water Cooled', category: 'DEWAS' },
  { product_name: 'NEO-20', kw: '1.5', hp: '2.0', pipe_size: '38 mm', head: '45-130 m', group_name: '4" Borewell Submersible Water Cooled', category: 'DEWAS' },
  { product_name: 'KS6-30', kw: '2.2', hp: '3.0', pipe_size: '50 mm', head: '30-90 m', group_name: '6" Borewell Submersible Water Cooled', category: 'DEWAS' },
  { product_name: 'KS6-50', kw: '3.7', hp: '5.0', pipe_size: '65 mm', head: '40-140 m', group_name: '6" Borewell Submersible Water Cooled', category: 'DEWAS' },
  { product_name: 'KS6-75', kw: '5.5', hp: '7.5', pipe_size: '65 mm', head: '60-200 m', group_name: '6" Borewell Submersible Water Cooled', category: 'DEWAS' },
  { product_name: 'KS6-100', kw: '7.5', hp: '10.0', pipe_size: '80 mm', head: '80-250 m', group_name: '6" Borewell Submersible Water Cooled', category: 'DEWAS' },
  { product_name: 'KS6-150', kw: '11.0', hp: '15.0', pipe_size: '80 mm', head: '100-300 m', group_name: '6" Borewell Submersible Water Cooled', category: 'DEWAS' },
  { product_name: 'KS7-75', kw: '5.5', hp: '7.5', pipe_size: '65 mm', head: '60-180 m', group_name: '7" Borewell Submersible Water Cooled', category: 'DEWAS' },
  { product_name: 'KS7-100', kw: '7.5', hp: '10.0', pipe_size: '80 mm', head: '80-220 m', group_name: '7" Borewell Submersible Water Cooled', category: 'DEWAS' },
  { product_name: 'KS8-150', kw: '11.0', hp: '15.0', pipe_size: '100 mm', head: '80-240 m', group_name: '8" Borewell Submersible Water Cooled', category: 'DEWAS' },
  { product_name: 'KS8-200', kw: '15.0', hp: '20.0', pipe_size: '100 mm', head: '100-280 m', group_name: '8" Borewell Submersible Water Cooled', category: 'DEWAS' },
  { product_name: 'JOS ULTRA-3', kw: '2.2', hp: '3.0', pipe_size: '65 x 50 mm', head: '10-24 m', group_name: 'Three Phase Openwell Submersible', category: 'DEWAS' },
  { product_name: 'JOS ULTRA-5', kw: '3.7', hp: '5.0', pipe_size: '80 x 65 mm', head: '12-32 m', group_name: 'Three Phase Openwell Submersible', category: 'DEWAS' },
  { product_name: 'JOS ULTRA-7.5', kw: '5.5', hp: '7.5', pipe_size: '100 x 80 mm', head: '14-38 m', group_name: 'Three Phase Openwell Submersible', category: 'DEWAS' },
  { product_name: 'JVS-5', kw: '3.7', hp: '5.0', pipe_size: '80 mm', head: '10-30 m', group_name: 'Vertical Openwell Submersible', category: 'DEWAS' },
  { product_name: 'JVS-7.5', kw: '5.5', hp: '7.5', pipe_size: '100 mm', head: '12-36 m', group_name: 'Vertical Openwell Submersible', category: 'DEWAS' },
];

export const END_SUCTION_PUMPS = [
  { product_name: 'NW-2', kw: '1.5', hp: '2.0', pipe_size: '50 x 40 mm', head: '10-22 m', flow_rate: '3-8 LPS', group_name: 'End Suction Standard Pumps', category: 'DEWAS' },
  { product_name: 'NW-3', kw: '2.2', hp: '3.0', pipe_size: '65 x 50 mm', head: '12-26 m', flow_rate: '5-12 LPS', group_name: 'End Suction Standard Pumps', category: 'DEWAS' },
  { product_name: 'NWD-2', kw: '1.5', hp: '2.0', pipe_size: '50 x 40 mm', head: '12-24 m', flow_rate: '3-8 LPS', group_name: 'End Suction Standard Pumps', category: 'DEWAS' },
  { product_name: 'NWD-3', kw: '2.2', hp: '3.0', pipe_size: '65 x 50 mm', head: '14-28 m', flow_rate: '5-12 LPS', group_name: 'End Suction Standard Pumps', category: 'DEWAS' },
  { product_name: 'KE-2', kw: '1.5', hp: '2.0', pipe_size: '50 x 40 mm', head: '10-20 m', flow_rate: '4-10 LPS', group_name: 'End Suction Standard Pumps', category: 'DEWAS' },
  { product_name: 'KE-3', kw: '2.2', hp: '3.0', pipe_size: '65 x 50 mm', head: '12-25 m', flow_rate: '6-14 LPS', group_name: 'End Suction Standard Pumps', category: 'DEWAS' },
  { product_name: 'KE-5', kw: '3.7', hp: '5.0', pipe_size: '80 x 65 mm', head: '14-30 m', flow_rate: '8-20 LPS', group_name: 'End Suction Standard Pumps', category: 'DEWAS' },
  { product_name: 'KH-3', kw: '2.2', hp: '3.0', pipe_size: '65 x 50 mm', head: '16-32 m', flow_rate: '5-14 LPS', group_name: 'End Suction High Head Pumps', category: 'DEWAS' },
  { product_name: 'KH-5', kw: '3.7', hp: '5.0', pipe_size: '80 x 65 mm', head: '20-40 m', flow_rate: '8-22 LPS', group_name: 'End Suction High Head Pumps', category: 'DEWAS' },
  { product_name: 'KHDT-5', kw: '3.7', hp: '5.0', pipe_size: '65 x 50 mm', head: '24-48 m', flow_rate: '4-12 LPS', group_name: 'End Suction Two Stage Pumps', category: 'DEWAS' },
  { product_name: 'KHDT-7.5', kw: '5.5', hp: '7.5', pipe_size: '80 x 65 mm', head: '30-60 m', flow_rate: '6-16 LPS', group_name: 'End Suction Two Stage Pumps', category: 'DEWAS' },
  { product_name: 'SR-5', kw: '3.7', hp: '5.0', pipe_size: '65 x 50 mm', head: '30-70 m', flow_rate: '2-8 LPS', group_name: 'End Suction Multistage Pumps', category: 'DEWAS' },
  { product_name: 'SR-10', kw: '7.5', hp: '10.0', pipe_size: '80 x 65 mm', head: '50-120 m', flow_rate: '5-15 LPS', group_name: 'End Suction Multistage Pumps', category: 'DEWAS' },
];
